### ISSUE TITLE
0.3 版的多master 多node 方案  etcd 的bug 

### ISSUE THREAD

**Issue by or0or1** [easzlab/kubeasz#288]
安装后， 一直报错：

localhost etcd: rejected connection from "192.168.2.55:55152" (error "remote error: tls: bad certificate", ServerName "")

etcd各种节点互相类似上述错误。

**Comment by gjmzj** [comment]
应该是你的集群配置清理不干净，虽然99.clean.yml的可以清理集群，但是它也只是按照现有 /etc/ansible/hosts里面配置的节点去清理；如果你在执行99.clean.yml前把/etc/ansible/hosts搞乱了，那么也清理不干净；

**Comment by linleybao** [comment]
按照文档安装1到3步骤成功，在执行第4步安装kube-master是报相同的错误
`[root@master01 ~]# systemctl status etcd
● etcd.service - Etcd Server
   Loaded: loaded (/etc/systemd/system/etcd.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2018-07-15 23:50:57 CST; 13min ago
     Docs: https://github.com/coreos
 Main PID: 2546 (etcd)
   Memory: 528.0K
   CGroup: /system.slice/etcd.service
           └─2546 /opt/kube/bin/etcd --name=master01 --cert-file=/etc/etcd/ssl/etcd.pem --key-file=/etc/etcd/ssl/etcd-key.pem --peer-cert-file=/etc/etcd/ssl/etcd.pem --peer-key-file=/etc/e...

Jul 16 00:02:03 master01 etcd[2546]: rejected connection from "172.16.1.170:33386" (error "EOF", ServerName "")
Jul 16 00:02:08 master01 etcd[2546]: rejected connection from "172.16.1.170:33388" (error "remote error: tls: bad certificate", ServerName "")
Jul 16 00:02:28 master01 etcd[2546]: rejected connection from "172.16.1.170:33390" (error "EOF", ServerName "")
Jul 16 00:02:34 master01 etcd[2546]: rejected connection from "172.16.1.170:33392" (error "remote error: tls: bad certificate", ServerName "")
Jul 16 00:02:54 master01 etcd[2546]: rejected connection from "172.16.1.170:33394" (error "EOF", ServerName "")
Jul 16 00:03:00 master01 etcd[2546]: rejected connection from "172.16.1.170:33396" (error "remote error: tls: bad certificate", ServerName "")
Jul 16 00:03:20 master01 etcd[2546]: rejected connection from "172.16.1.170:33398" (error "EOF", ServerName "")
Jul 16 00:03:26 master01 etcd[2546]: rejected connection from "172.16.1.170:33400" (error "remote error: tls: bad certificate", ServerName "")
Jul 16 00:03:46 master01 etcd[2546]: rejected connection from "172.16.1.170:33402" (error "EOF", ServerName "")
Jul 16 00:03:52 master01 etcd[2546]: rejected connection from "172.16.1.170:33404" (error "remote error: tls: bad certificate", ServerName "")`
请问是证书制作过程中有问题吗？

**Comment by gjmzj** [comment]
可能是环境不干净有其他组件在连接这个新的etcd集群
$ kubectl get cs
$ ansible etcd -m shell -a 'systemctl status etcd'

**Comment by linleybao** [comment]
Hi 	or0or1 ，
你的ansible节点和master节点在同一个主机上吗？我安装单master多node部署时，ansible和master在不同点上，就会报与你相同的错误。然后我把ansible和master在同一个节点上，就可以启动成功。

**Comment by ZPJeck** [comment]
原环境有遗留，应该怎么解决呢？

**Comment by ovwane** [comment]
## 服务器时间不同步。
```
Aug 14 14:29:14 master3 etcd[2714]: health check for peer 70a3d0d7ce567216 could not connect: x509: certificate has expired or is not yet valid
Aug 14 14:29:14 master3 etcd[2714]: health check for peer 70a3d0d7ce567216 could not connect: x509: certificate has expired or is not yet valid
Aug 14 14:29:14 master3 etcd[2714]: health check for peer b61c819edaec2d9a could not connect: x509: certificate has expired or is not yet valid 
```
